name: nichts iOS Build

"on":
  workflow_dispatch:

jobs:
build:
runs-on: macos-15

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Node
    uses: actions/setup-node@v4
    with:
      node-version: 24

  - name: Install dependencies
    run: npm install

  - name: Install Capacitor CLI
    run: npm install --no-save @capacitor/cli

  - name: Capacitor copy
    run: npx cap copy ios

  - name: Xcode build
    run: |
      xcodebuild \
        -project ios/App/App.xcodeproj \
        -scheme App \
        -sdk iphoneos \
        -configuration Debug \
        -destination 'generic/platform=iOS' \
        -derivedDataPath ios/build \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGNING_REQUIRED=NO \
        build

  - name: Check build
    run: |
      echo "Suche nach App.app..."
      find ios/build -name "App.app" -type d -print

  - name: Upload iOS build
    uses: actions/upload-artifact@v4
    with:
      name: nichts-ios-build
      path: ios/build/Build/Products/Debug-iphoneos/App.app
